### ISSUE TITLE
Produce CleanUpEntries screenshot using TextFX

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#245]
The screenshot at https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/CleanupEntries.md is outdated. It should be generated by using TestFX somehow.

(New highlighted screenshot: https://github.com/koppor/jabref/issues/349#issuecomment-547738365)

**Comment by koppor** [comment]
Refs https://github.com/JabRef/user-documentation/issues/199

**Comment by tobiasdiez** [comment]
Seems to be a special case of #199 (nearly all screenshots are outdated...)
