### ISSUE TITLE
Explain that comments from a PDF are displayed

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#248]
![grafik](https://user-images.githubusercontent.com/1366654/69026238-7e959f00-09ca-11ea-8c07-6eed4b598362.png)

**Comment by Siedlerchr** [comment]
Link a new PDF file to JabRef
Mark or comment something in the PDF.
In the entry editor, you can now select the tab "File annotations" and you will see the content you have highlighted or commented on in the PDF.
If you have multiple PDFs linked to the entry, you can select the document as well in the File Annotation tab
