### ISSUE TITLE
Should we use variants for different versions?

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/user-documentation#249]
Gitbooks support variants https://docs.gitbook.com/editing-content/variants, which would allow us to have different documentations for 4.3.1 and 5.0 (instead of having to add text saying "this does not apply to version xyz). Handled via git branches here. Disadvantage: changes to one variant need to be propagated to the other variants (manually?).

@koppor what do you think?

**Comment by koppor** [comment]
Our current stream of the development seems to propagate to use only the latest version.

On the one hand I see that we don't document the back-and-forth switching (https://github.com/JabRef/user-documentation/issues/227). On the other hand, we don't port all functionality to 5.0 (https://github.com/JabRef/jabref/issues/4719). Seeing our development power, I would keep focusing on getting 5.0 stable and complete - and even putting new features to it to have users migrating.

The variants are interesting for translating the help though. Have to check whether crowidn supports branches.
