### ISSUE TITLE
Rework command line arguments

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/user-documentation#250]
In 5.0 the `jar` file is gone, thus the beginning of https://docs.jabref.org/general/commandline needs to be completely reworked.

Triggered by: https://discourse.jabref.org/t/command-line-on-a-mac-os-installation/1879

**Comment by mlep** [comment]
@tobiasdiez  At the moment, the jar file is not mentioned anymore in https://docs.jabref.org/general/commandline  .
Can be closed?

**Comment by tobiasdiez** [comment]
yes, thanks a lot!
