### ISSUE TITLE
Add preferences dialog

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#252]
- Google for "JabRef preferences" does not point to docs.jabref.org directly
- In docs.jabref.org, searching for "preferences" does not reveal a page on the preferences
- In https://docs.jabref.org/setup, there is no heading "Preferences"

Add a page with a screenshot of the preferences to https://github.com/JabRef/user-documentation/tree/master/en/setup

Refs https://github.com/koppor/jabref/issues/177

**Comment by tobiasdiez** [comment]
I think a new page is not necessarily, but the main page https://docs.jabref.org/setup should indeed contain information about the preference dialog.
