### ISSUE TITLE
Add hint on Snap store

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#267]
Add to FAQ? That JabRef is also avaiable as a snap?
 https://snapcraft.io/jabref

**Comment by koppor** [comment]
I already added it to our installation hints at https://docs.jabref.org/general/installation. 

![grafik](https://user-images.githubusercontent.com/1366654/78111023-513b1200-73fc-11ea-8412-cfb4881d1896.png)


I don't want to duplicate information, so no further action taken here.
