### ISSUE TITLE
Discourse : dead link to FAQ

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#282]
At https://discourse.jabref.org/, The Discourse menu allows to access the FAQ.
See bottom right-hand corner of this screen copy:
![DiscourseFAQ](https://user-images.githubusercontent.com/6931104/83045738-49879a80-a046-11ea-923a-451da145a187.png)

It opens the page https://www.jabref.org/faq/ , which does not exist anymore.
Note: the FAQ is now at https://docs.jabref.org/faqgeneral

**Comment by Siedlerchr** [comment]
Refs #281  There are some more redirects we need

**Comment by tobiasdiez** [comment]
Thanks! This particular link should be fixed now.

**Comment by mlep** [comment]
Indeed, it works. Thanks!
