### ISSUE TITLE
Subsections are mostly invisible, giving the feeling there is no documentation

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#299]
I have been trying to understand why some help pages (organize, collect, configuration) get many views and a bad rating in GitBook analytics.

I believe this comes from the current layout of the JabRef documentation, which puts the emphasis on the main panel and keeps the table of content out of the user field-of-view.
For example, consider the page [configuration](https://docs.jabref.org/setup):
![Capture du 2020-09-01 21-55-17](https://user-images.githubusercontent.com/6931104/91899745-e4bf8a00-ec9d-11ea-8b5d-06543eaa83eb.png)
When you come to this page looking for information about JabRef configuration, you see the title, one paragraph giving some general information, and, maybe, the two boxes below to go to the previous and next sections.
Your eyes are not directed to the part of the table of content located to the bottom left-hand corner, i.e. your vision misses the part where the sensible information is located!
So, I believe that users come to this page, are disappointed, eventually click on the "sad smiley", and leave.

One can note that the page [cite](https://docs.jabref.org/cite) is not rated in GitBook Analytics. No user cared about its content? Not exactly: this page is simply a table of content by itself, hence the user probably simply clicks on the item of interest and (happily) leaves the page.
Conversely, the main pages [organize](https://docs.jabref.org/finding-sorting-and-cleaning-entries) (note: a few hours ago, there was one line of text only) and [collect](https://docs.jabref.org/collect) have a bad rating. And they look like the page [Configuration](https://docs.jabref.org/setup).

My suggestions:
- include (automatically) the table of contents in the main pages (like in the [cite](https://docs.jabref.org/cite) page)
- in the right panel make the subsections more attractive to the eye. Currently  they are dimmed compared to the other sections But I do not think that will be have a significant effect.

Any thought?

**Comment by tobiasdiez** [comment]
I agree! We cannot change the style but adding a table of contents for these generic header pages is a good idea.

**Comment by mlep** [comment]
@tobiasdiez 
The [cite page](https://docs.jabref.org/cite) as a table of content, but the markdown file is empty (except for the title). So I guess the table of content is added for empty page.
Any idea to get the table of content automatically for non-empty pages?

**Comment by mlep** [comment]
I have just started to add a ToC to each header page:
- https://docs.jabref.org/collect
- https://docs.jabref.org/cite

I am planning to continue.
If you want me to stop, please, tell me!

**Comment by tobiasdiez** [comment]
I like it!

**Comment by mlep** [comment]
Thanks.
So, I will continue.

**Comment by Siedlerchr** [comment]
LGTM!

**Comment by mlep** [comment]
Done to all main sections
