### ISSUE TITLE
Search engines: Provide all information for each of them

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#301]
Many pages describing a search engine get bad ratings.
These pages mostly describe what the search engine is about. So, I guess this is not what the users expect. They probably come with an issue, and such information does not provide a solution.

In fact, the issue-solving part, is in the main page [Searching externally using Online Services](https://docs.jabref.org/collect/import-using-online-bibliographic-database).

I suggest to copy/paste most of the text of the main page to each search engine. I know it may look dumb, but that will provide direct information to the users.

Any thought?

Note: the main page ([Searching externally using Online Services](https://docs.jabref.org/collect/import-using-online-bibliographic-database)) get a bad rating too, but I have no idea why...

**Comment by tobiasdiez** [comment]
I agree, in their current form these pages are essentially useless. Most users should probably know what "arXiv" is when they visit that page. 

What about having a list of all fetchers in https://docs.jabref.org/collect/import-using-online-bibliographic-database similar to how its done https://docs.jabref.org/collect/add-entry-using-an-id ? I would like that more than copy & past information from the main page to each fetcher.

**Comment by mlep** [comment]
Done in https://github.com/JabRef/user-documentation/commit/ead19aa7ec71099fa89a1f52253bef8baa8794bb
