### ISSUE TITLE
Advertise for discourse forum

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#302]
When a user comes to what it looks like the right help page and do not find the information he/she looks for, he/she is kind of stuck.

To help him/her and keep him/her in the community, I suggest to add at the bottom of each help file a hint frame with a link to our discourse help forum. Something like:
````
{% hint style="info" %}
Could not solve your issue? [Ask the JabRef community](https://discourse.jabref.org/c/help/7).
{% endhint %}
````

Any though?

PS: can a footer can be added automatically, or individual copy-paste would be needed?

**Comment by mlep** [comment]
Here is an example: https://docs.jabref.org/collect/add-entry-manually

Be careful: if you do not complain, I will add it everywhere! :wink:

**Comment by tobiasdiez** [comment]
Mhhh, I'm a but unsure if this is really helpful. It's kind of admitting that the help is not good, so you need to ask elsewhere if you want to get satisfying answers - of course, even the best documentation leaves question open...

What about a more miniamal approach and adding the link to the forum in the sidebar?

**Comment by mlep** [comment]
A link on the sidebar is a good idea!
But I do not know how to implement it...

**Comment by tobiasdiez** [comment]
It's now implemented.

(You can add links using the "New" button below the links in the sidebar.)

**Comment by mlep** [comment]
Footer removed (https://github.com/JabRef/user-documentation/commit/1799ed6a0ac74cfbde9d8e97d3db6743bd8440dc).

Oh, that simple to add the link!  Great!
