### ISSUE TITLE
Add by ID: DOI vs mEDRA vs crossref? Title?

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#304]
Two questions about the "Add by ID" feature (https://docs.jabref.org/collect/add-entry-using-an-id):

1) When selecting the ID type "DOI", "mEDRA" or "Crossref", the references are fetched based on the DOI. What is the difference between the three ID type?
Note: the DOI section of the help mentions `JabRef uses http://dx.doi.org/ (provided by http://crossref.org/) to convert the given DOI to a new entry.` (I am not the author :wink:). This makes the difference between ID type "DOI" and "Crossref" even more obscure.

2) What does the ID type "Title" mean? Based on the source code (https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/TitleFetcher.java), it looks like it is related to DOI, but it does not make sense to me.

**Comment by Siedlerchr** [comment]
It's really a bit confusing, probably also related to the fact that the list of IDFetchers is created automatically based on the classes implementing the interface.

DOIs are handled by multple agencies: https://www.doi.org/registration_agencies.html
The normal DOI fetcher queires dx.doi.org with the DOI and gets bibtex back. However, this does not work for all DOIs. Only works for CrossRef and some others. DOIs, I think. It's complicated. No one of us really knows it. And there isn't event a prefix to distinguish DOIs manually. And don't get me started on the EU Publications from oc.europa. They always return back the website and not bibtex.

For DOIs belonging to Medra, it doesn't return anything or had problems with umlauts so we need to implement a Medra DOI fetcher
For the dialog:
1. Select DOI -> JabRef checks dx.doi.org : If not found then the Medra DOI Fetcher is called.
2. Enter a Medra DOI in the Medra Fetcher: Medra fetcher gets called directly
3. CrossRef: CrossRef fetcher is called directly
4.  Title fetcher:
The title fetcher is doing some magic. You can enter the title of a paper and JabRef calls CrossRef which returns a DOI based on the title. Then 1. is called again


This is the method which returns CrossRef:
https://github.com/JabRef/jabref/blob/1305d06fe2ceb4e3f278c8235ff8f2b588562129/src/main/java/org/jabref/logic/importer/WebFetchers.java#L69

**Comment by mlep** [comment]
A bit confusing, indeed. And thank you for attempting a clarification.
I am going to try to alter the help to account for your comments.
