### ISSUE TITLE
Missing help pages: creating them and leaving them empty

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#308]
I have identified some items that should have an help page:
- Manage keywords
- Edit preamble
- Send as email
- Preview style

(there may be other ones)

I propose to create the corresponding pages and leave them mostly empty, just with a message asking for contribution (see https://docs.jabref.org/collect/import )
To me it is a better approach than opening an issue here, and calling for their creation and writing because:
- users will see the empty pages and may contribute directly (which user will come to the list of issues when an information is missing in the help pages?)
- users can "vote" to show their disappointment, which give information about pages that should be completed more "urgently".

Please, let me know what you think.

**Comment by koppor** [comment]
We had the empty pages for years and no one new ever contributed.

I think, one approach could be to ask in the forum when someone writes on a specific topic. Then, one can coach the contributor.

Drive-by contribution for documentation unfortunately is very seldom.

**Comment by mlep** [comment]
How to keep track of the missing help pages?
One issue with a list of all the identified missing help pages, or one issue per missing help page?

**Comment by Siedlerchr** [comment]
I think one issue with a checklist of all pages makes it easier. Github will also show the "progress" of the issue then in the overview

**Comment by mlep** [comment]
OK, I will do so.
