### ISSUE TITLE
"BibTeX field" to be replaced by ???

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#315]
In the interface and in the help, "BibTeX field" is mentioned, while the field is not BibTeX specific (i.e. it could be a biblatex field too).
Here is an example from the group interface:
![Capture du 2020-10-02 12-53-51](https://user-images.githubusercontent.com/6931104/94916361-d6d47300-04ae-11eb-852b-194393ac7e91.png)

Like "bibtexkey" was replaced by "citationkey", I propose to replace "BibTeX field" and "biblatex field" (when the field is not specific to BibTeX or biblatex).
What would be a good replacement:
- bibentry field?
- bibliographic field?
- entry field?
- ...?

**Comment by tobiasdiez** [comment]
I would simply use "field" without any qualifier. In most cases, the distinction between bibtex and biblatex, and JabRef's bultin-fields (like groups, or entrytype) are not important.

In the above screenshot, one can simply write "Generate groups from keywords in the following field:"

**Comment by mlep** [comment]
@tobiasdiez OK, thanks!
