### ISSUE TITLE
https://layouts.jabref.org ?

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#316]
The help (https://docs.jabref.org/advanced/resources) mentions the URL https://layouts.jabref.org as a repository of export filters, but it returns a 404 error.
Is there a plan to put it back online?
Or shall the URL be replaced by https://github.com/JabRef/layouts.jabref.org?

**Comment by koppor** [comment]
Some GitHub hickup. I needed to add `index.html` to get the redirection to the GitHub repository working.

Somehow puts back the issue https://github.com/koppor/jabref/issues/392 in my mind...
