### ISSUE TITLE
Add names of save actions

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#318]
A user reported at https://github.com/JabRef/jabref/issues/7012#issuecomment-707840679

    11:54:05.303 [JavaFX Application Thread] WARN org.jabref.logic.citationkeypattern.BracketedPattern - Key generator warning: unknown modifier 'remove_braces_formatter'.

I think, the documentation page for the formatters is https://github.com/JabRef/user-documentation/blob/master/en/finding-sorting-and-cleaning-entries/saveactions.md. There, the intenral name of the formatter (`getKey()`, https://github.com/JabRef/jabref/blob/e955c46850e4738830198a889c3f09870b88ab30/src/main/java/org/jabref/logic/formatter/bibtexfields/RemoveBracesFormatter.java#L16) is not listed. I think, it should be listed as the user can include it at https://docs.jabref.org/setup/citationkeypatterns#modifiers (can't he?).

Should there also be a link from https://docs.jabref.org/setup/citationkeypatterns#modifiers to the save actions?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> Should there also be a link from https://docs.jabref.org/setup/citationkeypatterns#modifiers to the save actions?

Yes, there should be a link. I did not know "save actions" were a thing 😛 

> I think, it should be listed as the user can include it at https://docs.jabref.org/setup/citationkeypatterns#modifiers (can't he?).

They can all be accessed as "modifiers", yes. But the user, most likely, should not. The "special field markers" sometimes remove latex, sometimes remove spaces, and sometimes does neither (I am speculating that they were intended as citation keys and the use of the "bracketed expressions" has expanded?). I don't think they can be used with consistent results, but perhaps I am being overly paternalistic on this subject.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Oups, and I missed the point. Yes, I'd agree that the `getKey()` should be listed.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
"Save actions" exists both in https://github.com/JabRef/user-documentation/blob/master/en/advanced/saveactions.md and https://github.com/JabRef/user-documentation/blob/master/en/finding-sorting-and-cleaning-entries/saveactions.md, is there some recommended way of referencing it?

**Comment by Siedlerchr** [comment]
I think it makes sense to have them all in one place and just link from the sorting and cleaning to them

**Comment by mlep** [comment]
It looks like the good page (the one displayed at help.jabref.org is this one: https://github.com/JabRef/user-documentation/blob/master/en/finding-sorting-and-cleaning-entries/saveactions.md

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
> It looks like the good page (the one displayed at help.jabref.org is this one: https://github.com/JabRef/user-documentation/blob/master/en/finding-sorting-and-cleaning-entries/saveactions.md

That does seem to be the case. I don't really know what is going. I'll link to this one for now.

**Comment by koppor** [comment]
There should be only one file. The other one can be deleted. Please add a redirect from the deleted page to the new page into https://github.com/JabRef/user-documentation/blob/master/.gitbook.yml

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
I am taking a look at this

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Among others, I cannot use `RemoveNewlinesFormatter` for abstracts, should that be addressed?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Note, if it cannot be accessed from Formatters#getAll() (which it cannot), it also cannot be used as a modifier.

**Comment by Siedlerchr** [comment]
It's an internal formatter only. It should then not be documented.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
So the documentation for the ones that cannot (currently) be used should be removed? (e.g., https://github.com/JabRef/user-documentation/blob/master/en/finding-sorting-and-cleaning-entries/saveactions.md#remove-line-breaks)

**Comment by koppor** [comment]
@k3KAW8Pnf7mkmdSMPHz27 Yes, please remove the ones not available to the user. Currently, the description does not contain any examples, thus it is no loss to just delete the text.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment]
Ok. I'll not add "Replace Unicode ligature" which is the default for "All-text-fields", but cannot be added manually. If it gets added to `Formatters#getAll` it can be included.
