### ISSUE TITLE
[Devdocs]: Add code/hint not to use JabRefPreferences.getInstance()

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#337]
Use PreferencesService

**Comment by mlep** [comment]
@Siedlerchr Since this repository is for user documentation and that the development doc is in https://github.com/JabRef/jabref/tree/master/docs , this issue may be better in https://github.com/JabRef/jabref/issues , no?

**Comment by Siedlerchr** [comment]
I should probably have moved it to koppor

**Comment by koppor** [comment]
Yes, please open it at https://github.com/koppor/jabref/issues to keep the number of issues in our main repository low.
