### ISSUE TITLE
Update description of icon for automatically linked files

### ISSUE THREAD

**Issue by martinfalke** [JabRef/user-documentation#353]
As of merged pull request [JabRef/7484](https://github.com/JabRef/jabref/pull/7484), the [documentation for 'Auto linking files'](https://docs.jabref.org/finding-sorting-and-cleaning-entries/filelinks#auto-linking-files) is outdated.

**Current:**
- The visual cue for auto-linked files is described as a "suitcase" icon

Desired update:
- The visual cue is described as reducing the opacity of the file entry with a prepended icon that shows a link with a plus on top of it, as shown in the screenshots of [the PR](https://github.com/JabRef/jabref/pull/7484#issuecomment-792630296)

**Comment by mlep** [comment]
Thank you for identifying this issue.
The name of the icon is not correct
