### ISSUE TITLE
Multi Language Support

### ISSUE THREAD

**Issue by starsareintherose** [JabRef/user-documentation#363]
Do you have any plan to add more language support for the `https://docs.jabref.org/`. If you need. I would like to work on the translation for the docs.

**Comment by koppor** [comment]
We once had the multiple languages. However, they were not maintained. The energy of the translators was put into keeping the translations of the main program updated.

As a supporter of JabRef, I would ask to work on the English documentation. Maybe start at https://github.com/JabRef/user-documentation/issues/278.

**Comment by koppor** [comment]
Another option is to work on a translation + update of the German documentation https://github.com/JabRef/manuals.jabref.org/tree/master/de. I liked the flow and the content there. However, it was never translated to English and updated to the latest version.

**Comment by Siedlerchr** [comment]
Can't we integrate this with Crowdin somehow? 
Crowdin supports markdown. But I wonder how it works with gitbook

**Comment by starsareintherose** [comment]
I have worked on ZH-CN for about 10% of all on Crowdin.

**Comment by koppor** [comment]
I put it on our agenda for the next developer's call (https://github.com/JabRef/jabref/wiki/Minutes).

My main concern is that the current English documentation is not in a good state; energy should be better put in that in contrast to translate a bad documentation in another language. (Historical remark: This was the decision back in 2019 when we deleted all non-English help files. They were not updated. We had Chinese, German, French, Indian, and Japanese - The deletion commit is https://github.com/JabRef/help.jabref.org/commit/d599612374642f54aea264114b534213f5e0ac2c#diff-fed70c1c91898cdecb00018dd9bf4abd1a7d8ccb118597186b7162feab5f0490)

Another option is to create new documentation in Chinese, translate that back to English, check it whether it is correct and then translate potential updates back.

Side comment: We already had lot of Chinese text. See https://github.com/JabRef/help.jabref.org/commit/5a5a13a6b439a1e6026914b7bac60f8510922b7f#diff-fed70c1c91898cdecb00018dd9bf4abd1a7d8ccb118597186b7162feab5f0490. @starsareintherose I cannot rate the quality of that text, can you?

It would cost me about 10 hours to do following steps:

- Setup crowdin to support user documentation
- Port the existing texts to our new documentation structure

We should decide whether I (or someone else) should put this effort in this - or whether we should spend that time in bug fixing, ...

The arguments on the positive side, I would say that it could attract more users to JabRef - and maybe some new coders --> the main issue of JabRef is the number of open issues and missing features.

If you want, we can also discuss via email. You find my email in my GitHub profile.

**Comment by starsareintherose** [comment]
I've sent the email.

**Comment by mlep** [comment]
I share the view of @koppor: the English help is not in a state that allows a translation (currently, you will translate text that does not represent the way JabRef 5.* works). I guess we should first concentrate on getting the current help up-to-date. So the more urgent question is: how to get more contribution in improving the current help?
