### ISSUE TITLE
Links in Architectural Decisions lead to nowhere

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/user-documentation#379]
Links on the page https://devdocs.jabref.org/adr lead to 404 error.

**Solution:**

"You have to change the name of the folder in the link. For example, in https://github.com/JabRef/jabref/tree/master/docs/adr/0004-use-mariadb-connector.md
you have to write main instead of master" - [Rewolfnus A](https://discourse.jabref.org/u/rewolfnusA)

**Comment by Siedlerchr** [comment]
Devdocs were not synced properly with gitbook. This is fixed now

**Comment by ThiloteE** [comment]
Thanks :) I was about to work on this today. Lucky!
