### ISSUE TITLE
GitBook: Please, review of change requests

### ISSUE THREAD

**Issue by mlep** [JabRef/user-documentation#381]
Before, I could merge directly my changes to the documentation. Because this is not possible anymore (probably a change in the workflow), it requires the change requests to be reviewed.

Who is in charge of this review?
Please, could you look at (and merge) my change requests? (3 change requests from me waiting at the moment).

Cheers.

**Comment by Siedlerchr** [comment]
Hi, I updated your rights. You should now be able to merge changes again. I hope the sync works. There have been some issues wth GitBook recently... Its annoying

**Comment by mlep** [comment]
Thanks!
Yeah, gitbook (dys)functionings are annoying (and it is not recent to me...).
