### ISSUE TITLE
Word  365 References on Mac: You cannot select a custom Sources file

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#387]
In Word 365 you cannot select a custom XML file with sources. In Windows (at least in earlier versions this was possible)

Go to References -> Manage references ->  You cannot select a custom sources
The sources.xml file (masterlist) is stored in
`~/Library/Containers/com.microsoft.word/Data/Library/Application Support/Microsoft/Office`

For Windows this seems to be possible:
https://www.officetooltips.com/word_365/tips/manage_sources.html

**Comment by Siedlerchr** [comment]
It needs to be documented at this page. Add a section on mac.
https://docs.jabref.org/cite/export-to-microsoft-word

**Comment by KievitJustin** [comment]
I would like to edit this page

**Comment by Siedlerchr** [comment]
After copying the sources.xml you have to restart Word, so any changes in the references list are visible
