### ISSUE TITLE
ajuda isso esta difícil de encontrar

### ISSUE THREAD

**Issue by Osmarbvo** [JabRef/user-documentation#389]

**Comment by Osmarbvo** [comment]
a issue é dificil de encontrar

**Comment by ThiloteE** [comment]
I only can assume you are a student of some sorts or somebody who is learning how to work with GitHub. I also assume, you are in this persons class: [Italo Santos](https://github.com/italo-07)

This here is the original official repository of Jabref, so probably not the place where you intended to open an issue at.

We are always happy people using and playing around with Jabref. Don't worry, no harm done. It would be nice, if you could relay to [Italo Santos](https://github.com/italo-07) we would not mind seeing some positive contributions to Jabref, apart from triggering a high number of first issues and first pull requests 😄😉

----
Só posso assumir que é um estudante de algum tipo ou alguém que está a aprender a trabalhar com GitHub. Presumo que esteja nesta turma de pessoas: [Italo Santos](https://github.com/italo-07)

Este aqui é o repositório oficial original do Jabref, por isso provavelmente não é o local onde pretendia abrir uma edição.

Somos sempre pessoas felizes por usar e brincar com o Jabref. Não se preocupe, não há mal nenhum. Seria bom, se pudesse transmitir para [Italo Santos](https://github.com/italo-07) não nos importaríamos de ver algumas contribuições positivas para o Jabref, para além de desencadear um elevado número de primeiras edições e primeiros pedidos de extracção 😄😉

Traduzido com a versão gratuita do tradutor - www.DeepL.com/Translator

**Comment by ThiloteE** [comment]
There are many ways how [contribution to Jabref](https://docs.jabref.org/contributing#i-am-not-a-programmer) could look like. Jabref also offers close cooperation with teachers and instructors. Check out the documentation [how Jabref could be integrated into your class](https://devdocs.jabref.org/teaching#how-to-integrate-jabref-in-your-class).

----

Há muitas maneiras de como [contribuição para Jabref](https://docs.jabref.org/contributing#i-am-not-a-programmer) poderia parecer. Jabref também oferece uma estreita cooperação com professores e instrutores. Consulte a documentação [como Jabref poderia ser integrado na sua turma](https://devdocs.jabref.org/teaching#how-to-integrate-jabref-in-your-class).
