### ISSUE TITLE
Update info about installation method for Linux  and Windows Portable versions for JabRef 5

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/user-documentation#390]
Following page seems outdated: https://docs.jabref.org/installation
There is contradictory information at https://docs.jabref.org/advanced/commandline

Multiple users reported error when trying to install Jabref on Linux:

e.g.
- https://github.com/JabRef/jabref/issues/8648
- https://discourse.jabref.org/t/jabref-5-1-linux-portable/2293

**Comment by ThiloteE** [comment]
On Windows 10: Clicking on `\Jabref\JabRef.exe` works.

**Comment by tobiasdiez** [comment]
Seems like the sync github <-> gitbook is broken again. I tried to trigger another sync but it reports a status of "0%" now for 1h. Let's see how it goes in a few hours.

**Comment by Siedlerchr** [comment]
I deleted and readded the  integration. Works now

**Comment by ThiloteE** [comment]
I confirm. :-) Closing this.
