### ISSUE TITLE
Remove specific mentioning of JDK version at instructions how to build from source 

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/user-documentation#393]
Page: https://docs.jabref.org/installation#building-from-source

Change following sentence:

"To build JabRef from source, you first need to have a working Java Development Kit 13 (JDK 13) and Git installed on your system."

to something like this:

"To build JabRef from source, you first need to have a working and up to date Java Development Kit (JDK) and Git installed on your system. Keep in mind that when a new JDK was released very recently, JabRef may not have been updated to work with the newest version yet."

As far as I am aware, JabRef does not have to be compiled with JDK 13 anymore and maintainers are trying to update JabRef to work with newest versions of JDK in a timely manner.

**Comment by Siedlerchr** [comment]
Must be JDK17 now. Seems like it was lost from removing the gitbook integration

**Comment by Siedlerchr** [comment]
@ThiloteE  You should be able to directly edit the files here at github
