### ISSUE TITLE
Group dynamic collection: RegEx for 'owner' field returning empy and non-three-letters

### ISSUE THREAD

**Issue by CrocodileDandy** [JabRef/user-documentation#398]
### JabRef version

Other (please describe below)

### Operating system

Windows

### Details on version and operating system

Windows 10 21H2, JabRef 5.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I fail to find library entries where the `Owner` field is left empty using a dynamic group based on collection by a search for keywords and a regex.

I have a shared library where every user is required to use the setting to mark new entries with their username (General > Entry owner > ☑ Mark new entries with owner name). I want to check this by gathering the entries where the `Owner` field is empty (or does not match the required pattern) in a dynamic group.
For this purpose, I have created a dynamic group where entries are collected by searching for keywords in the `Owner` field using the following regex: `^(?![a-zA-Z]{3}$)`. This regex will match if the content of the field is different from three letters, either lower or upper case. I checked it on https://regex101.com/
Unfortunately, no entry is added to the group.

Is that normal behavior? What am I missing here?

To reproduce:
1. Install JabRef 5.1 (although testing on 5.7 led to the same behavior so you should be able to reproduce there).
2. Create some libraries entries, some with the `Owner` field filled with __three letters only__ and some left empty or with a different content.
3. Create a dynamic group where items are collected by searching for keywords in the `Owner` field using the following regex: `^(?![a-zA-Z]{3}$)`

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by ThiloteE** [comment]
Reopened because this could be something for JabRef's documentation and webpage. @CrocodileDandy, if you don't want to receive further notifications, you can unsubscribe them for this specific issue.

**Comment by Siedlerchr** [comment]
@ThiloteE  Go ahead and add it to the documentation ;)
