### ISSUE TITLE
Add video about PDF management

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#4]
Add a video explaining following steps:
1. Add entry using the DOI (Web Search -> DOI to BibTeX)
2. Drag'n'drop the PDF into the preview panel of the entry
3. JabRef then asks to rename the PDF according to the bibtex data

![grabbed_20160205-152148](https://cloud.githubusercontent.com/assets/1366654/12848780/2dd2dbae-cc1c-11e5-9bb4-b4b1925fd997.png)

**Comment by tobiasdiez** [comment]
The process is pretty self-explanatory now, so that I don't think we need a video for this. Although videos in general are a good idea...
