### ISSUE TITLE
Update Manage field names and content -> Automatic field editor

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#402]
In https://github.com/JabRef/jabref/pull/8892 the new Automatic Field Editor was introduced. It needs to be documented as well.

**Comment by Siedlerchr** [comment]
The dialog described here https://docs.jabref.org/finding-sorting-and-cleaning-entries/managing-field-names-and-their-content is no longer accessible.

**Comment by ThiloteE** [comment]
@HoussemNasri I just notice again, that we still have to do this T.T

**Comment by ThiloteE** [comment]
I created a pull-request in GitBook.

**Comment by ThiloteE** [comment]
I created a pull-request in GitBook.

**Comment by ThiloteE** [comment]
PR was merged. Documentation was added in commit ce23474028ab0d876eb10cda0f7e945e29cfc68d
