### ISSUE TITLE
Add page that describes how to customize the entry table

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#435]
The user can modify the list of column in the preferences

Add extra section on how to add columns for different file types
https://discourse.jabref.org/t/pdf-column-in-entry-table/3696/4?u=siedlerchr

**Comment by Tridecatrix** [comment]
Hey, I would like to work on this; can this issue be assigned to me?

**Comment by Tridecatrix** [comment]
@koppor This issue can now be closed!

**Comment by koppor** [comment]
> (I swear there is some way to link a PR with an issue such that closing the PR also closes the issue? couldn't figure out how to do it in this case tho)

Yes, there is. Here our template of the main repo to explain:

---

To ease organizational workflows I have linked the pull-request to the issue with syntax as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> <h2 id="linking-a-pull-request-to-an-issue-using-a-keyword">Linking a pull request to an issue using a keyword</h2>
> <p>You can link a pull request to an issue by using a supported keyword 
> in the pull request's description or in a commit message. The pull 
> request <strong>must be</strong> on the default branch.</p>
> <ul>
> <li>close</li>
> <li>closes</li>
> <li>closed</li>
> <li>fix</li>
> <li>fixes</li>
> <li>fixed</li>
> <li>resolve</li>
> <li>resolves</li>
> <li>resolved</li>
> </ul>
> <p>If you use a keyword to reference a pull request comment in another 
> pull request, the pull requests will be linked. Merging the referencing 
> pull request also closes the referenced pull request.</p>
> <p>The syntax for closing keywords depends on whether the issue is in the same repository as the pull request.</p>


### Example:
- ✅ `Fixes #xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fixes https://github.com/JabRef/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ✅ `Fixes https://github.com/Koppor/jabref/issues/xyz` links pull-request to issue. Merging the PR will close the Issue.
- ❌ `Fixes [#xyz](https://github.com/JabRef/jabref/issues/xyz)` links pull-request to issue. Merging the PR will **NOT** close the Issue.
