### ISSUE TITLE
Enhance "how to debug" with a hint to .bak files

### ISSUE THREAD

**Issue by koppor** [JabRef/user-documentation#447]
Follow up to https://github.com/JabRef/user-documentation/issues/439.

JabRef saves old versions of the library upon modification. These can also be used for debugging a bib file.

- Explain folder of .bak files
- Explain how to do a diff of two .bak files - Is [meld](http://meldmerge.org/) the tool we recommend and provide screenshots?

Development ideas:

- JabRef should offer the CLI option to compare to files so that a user can compare two .bak files using JabRef.

**Comment by ThiloteE** [comment]
Fixed via gitbook. Only requires review and merge.

**Comment by koppor** [comment]
Thank you for your work! Merged!
