### ISSUE TITLE
add new theme website link

### ISSUE THREAD

**Issue by ghost** [JabRef/user-documentation#460]
Hi

- [x] Maybe you can put a link to the themes website here ?

   https://docs.jabref.org/advanced/custom-themes

- [ ]  And maybe the forum can have a custom theme/exporter section for questions and for sharing the theme website?
   
   Because I think otherwise people won't even find the theme website because it's not linked to (except in my forum post which will sink to the bottom because I don't like to talk in public )

**Comment by ThiloteE** [comment]
@the-dino-girl, tagging you here, because you authored this issue.
I pinned your themes to the top of the help category in the forum. Creating a new category would probably be overkill, especially since most people will not create their own themes.
