### ISSUE TITLE
Update docs for keyword separator

### ISSUE THREAD

**Issue by colinldbd** [JabRef/user-documentation#468]
I found a potential need for improvement in the documentation for JabRef while trying to solve [issue#177](https://github.com/koppor/jabref/issues/177)

In the documenation for [JabRef](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups) the keyword separator TextField belong to the preference->Group:
<img width="1031" alt="image" src="https://github.com/JabRef/jabref/assets/16120094/42ad8ce3-609f-4025-9ef9-6347875ba212">

However, in the latest implementation, it's no longer there, now it's moved to preference->Entry:
![image](https://github.com/JabRef/jabref/assets/16120094/d71d1f3b-d9ad-4579-810e-028299f59485)

I suggest that we should update the documentation in [docs.jabref.org](https://docs.jabref.org/finding-sorting-and-cleaning-entries/groups) for this to avoid confusion.

**Comment by Daniel-Ruan** [comment]
My teammates and I from ANU would like to take on the task of updating the documentation for the keyword separator as outlined in issue #468. We believe we can contribute effectively to resolving this. Could you please assign this issue to us?

**Comment by lluukii** [comment]
I am a student in the Australian National University, and I am interested in working on this issue. Could you please assign this issue to me?
