### ISSUE TITLE
Create the documentation for the git support

### ISSUE THREAD

**Issue by lbenicio** [JabRef/user-documentation#470]
As a developer, I want to be able to understand the JabRef git integration and how it handles pulls and pushes to the remote repository as well as local.

**Comment by koppor** [comment]
This is for https://github.com/JabRef/jabref/pull/10586.

As **user** one wants to know how it works. - An initial text can be based on https://www.reddit.com/r/LaTeX/comments/1179mdx/comment/j9az1u9/?utm_source=reddit&utm_medium=web2x&context=3

However, https://github.com/JabRef/jabref/pull/10586 needs to be adapted accordingly.
