### ISSUE TITLE
Rendering issue in FAQ

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/user-documentation#517]
<img width="889" alt="grafik" src="https://github.com/user-attachments/assets/0e9deed9-68e8-4457-bd9c-6e7807920de0">

**Comment by Tridecatrix** [comment]
Hi Siedlerchr,

A clarification regarding this issue; I am not entirely clear what the problem is judging from the screenshot? It seems perfectly readable to me, and the windows emoji is shown correctly. What is the expected rendering?

**Comment by Siedlerchr** [comment]
For me in  Firefox and in Chrome the Windows-Emoji is not rendering.
Also not on github https://github.com/JabRef/user-documentation/blob/main/en/faq/windows.md
https://docs.jabref.org/faq/windows#q-how-can-i-start-or-focus-jabref-with-hotkey-j-winj

**Comment by Siedlerchr** [comment]
Oh I just saw that this is the official icon. nevermind

**Comment by koppor** [comment]
Forgot to make a PR - I just removed the FAQ - think, this is more an esoteric wish? -- https://github.com/JabRef/user-documentation/commit/5f1f6d56042d174ef26cbf4fb6a5aa0845512f26
