### ISSUE TITLE
ElephantSQL is dicontinued

### ISSUE THREAD

**Issue by InAnYan** [JabRef/user-documentation#522]
The link on ElephantSQL is here: https://docs.jabref.org/collaborative-work/sqldatabase

https://www.elephantsql.com/blog/end-of-life-announcement.html

**Comment by Siedlerchr** [comment]
There's an issue in the melting pot with alternatives

Ruslan ***@***.***> schrieb am So., 6. Okt. 2024, 12:23:

**Comment by Siedlerchr** [comment]
Duplicate of https://github.com/JabRef/user-documentation/issues/494
