### ISSUE TITLE
Screenshots missing/broken on the Comments documentation page

### ISSUE THREAD

**Issue by Tridecatrix** [JabRef/user-documentation#527]
There are clearly screenshots meant to be on this page that are missing:
![Image](https://github.com/user-attachments/assets/1eee9a69-cff3-4733-93d1-dfe8fe130e73)

Links to the page online and on the Github repo:
- https://docs.jabref.org/finding-sorting-and-cleaning-entries/comment-on-an-entry 
- https://github.com/JabRef/user-documentation/blob/7b6bafd7df960e89c1af9e499c176a1a08032d77/en/finding-sorting-and-cleaning-entries/comment-on-an-entry.md.

I have tried to re-create the screenshots and make a PR accordingly, but the comments page demonstrates comments made by several different users, and I am not sure how to replicate that. If it requires using the SQL shared database feature then it really isn't worth the headache for me personally. If you can instead export the library to .bib and comments can be seen on other devices after importing the .bib on JabRef, then it might be possible for me to replicate those. In the former case I'll leave this issue to someone who is more familiar with JabRef; in latter case I'll try handle it myself.

**Comment by Siedlerchr** [comment]
Maybe you are still able to find them in the assets folder?
https://github.com/JabRef/user-documentation/tree/7b6bafd7df960e89c1af9e499c176a1a08032d77/en/.gitbook/assets

**Comment by Tridecatrix** [comment]
Hm good point, I just had a look and unfortunately if the file exists, it is not called `comment-` something. It doesn't help that in the Github version of the file, all it says is "broken reference". It is also in HTML format curiously even though the other image links I've seen are in Markdown format...
![Image](https://github.com/user-attachments/assets/ea271498-0f6b-4b3e-9180-602d1a5d4a44)

**Comment by koppor** [comment]
Fixed at be03098.

Background: We cleanup our images now and then. However, gitbook started to use `image` as name for all images. Thus, we overwrite some images.

---

Internal hints:

-  Use git to checkout an image from a comit: `git checkout a89d8c95785c38f93913fa543 -- "image (1).png"`
- Use GitHub to browse a certain file on a specific commit: https://github.com/JabRef/user-documentation/blob/a89d8c95785c38f93913fa543/en/advanced/autosave.md

**Comment by koppor** [comment]
Thank you for reporting @Tridecatrix 

> I have tried to re-create the screenshots and make a PR accordingly, 

So happy to see that you wanted to contribute. If you have time, you could work on some other issues listed at https://github.com/JabRef/user-documentation/issues.

> but the comments page demonstrates comments made by several different users, 

Yes

> and I am not sure how to replicate that. 

Just edit the bibtex source manually. The format is `comment-username` for the field. Thus, no need for some shared setup 😅

**Comment by Tridecatrix** [comment]
Thanks for the quick response and feedback! I will see what I can do :).
